# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Unittests

on: [push]

jobs:
  runtests:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 24.12
      uses: actions/setup-node@v1
      with:
        node-version: 24.12
    - name: Install dependencies
      run: npm install
    - name: Test
      run: npm run citest
